[package]
name = "legion_transform"
version = "0.3.0"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

license = "MIT"

[dependencies]
legion = { git = "https://github.com/TomGillen/legion.git", branch = "systems" }
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
rayon = "1.2.0"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
approx = "0.3"
ron = "0.5.1"
